Opal.queue(function(Opal) {/* Generated by Opal 1.8.2 */
  var $klass = Opal.klass, $return_val = Opal.return_val, $defs = Opal.defs, $nesting = [], nil = Opal.nil;

  return (function($base, $super) {
    var self = $klass($base, $super, 'Atome');

    
    return $defs(self, '$aui', $return_val("68ecd3a69502c7b04f0c8babec1b0cd0e9ff0f0ab87b47c5a70b80c52b4c3571"))
  })($nesting[0], null)
});
